### ISSUE TITLE
glslify@2

### ISSUE THREAD

**Issue by hughsk** [stackgl/glslify#31]
There's a few kinks in glslify as it stands that I think would be best addressed with a significant reshuffle in the code, potentially a rewrite. It's probably a good idea to keep these changes in mind while we're writing the book chapter, seeing as it'll be a while before that's released and it'd be a shame if it were already out of date by then.

Here's what's on my radar:

* [ ] use [static-module](http://npmjs.org/package/static-module) (#30, #10) for static analysis.
* [ ] try and improve error handling. Perhaps the transform could log errors client-side instead of throwing/emitting errors during the build?
* [ ] default to `sourceOnly`, and leave it up to a hypothetical `glslify-shader` package to do the rest?
* [ ] more documentation.
* [ ] make the API more consistent between node, the CLI and the browser (#8).
* [ ] make it simpler to write framework-specific wrappers, and test this by writing framework-specific wrappers.
 * [ ] `glslify-three`
 * [ ] `glslify-pex`?
* [ ] better hooks to ease writing packages such as `glslify-live`, `glslify-api` and `glslify-optimize`.
* [ ] tests!
* [x] refactor internal packages to make sync APIs available:
 * [x] glsl-tokenizer
 * [x] glsl-parser
 * [x] glsl-deparser
* [ ] leave a window open for first-class functions, or at least callbacks (#23)

I don't see any need to change the require syntax or the package resolution, so those should remain untouched. The above changes mostly boil down to making glslify wizardry easier and loosening the coupling between glslify and the rest of the stack.gl ecosystem, giving it the chance to work just as well as a standalone tool.

If anybody would like to chime in with their thoughts on any of the above, please do!
